=== AlejandroReyes1998/TecnoWeb/Tareas/cdtareastw/cdtareastw/38/esquema20.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="raiz">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="a" type="xs:string" minOccurs="2" maxOccurs="3"/>
				<xs:element name="b" type="xs:string" minOccurs="2" maxOccurs="3"/>
				<xs:element name="c" type="xs:string" minOccurs="2" maxOccurs="3"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AlejandroReyes1998/TecnoWeb/Tareas/cdtareastw/cdtareastw/38/xml20.xml
<raiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema20.xsd">
<a></a>
<a></a>
<b></b>
<b></b>
<b></b>
<c></c>
<c></c>
</raiz>
